main/urls.py
from django.urls import path
from . import views
from django.shortcuts import render


app_name = 'main'

urlpatterns = [
    path('', views.homepage, name = "homepage"),
    path('about/', views.about, name = "about"),
    path('about/<single_slug>', views.error_page, name = "error_page3"),
    path('team/', views.team, name = "team"),
    path('team/<single_slug>', views.error_page, name = "error_page4"),
    path('register/', views.register, name = 'register'),
    path('register/<single_slug>', views.error_page, name = 'error_page1'),
    path('login/', views.login_request, name = "login"),
    path('login/<single_slug>', views.error_page, name = 'error_page2'),
    path('logout/', views.logout_request, name = "logout"),
    path('notes/', views.department, name = "department"),
    path('notes/<single_slug>/', views.single_slug, name="single_slug"),
    path('notes/<slug:slug>/notes-list/', views.notes_list, name = "notes_list"),
    path('notes/<slug:slug>/notes-list/<int:pk>/', views.delete_notes, name = "delete_notes"),
    path('past-year-papers/', views.department, name = "papers_department"),
    path('past-year-papers/<single_slug>/', views.paper_single_slug, name="papers_single_slug"),
    path('past-year-papers/<slug:slug>/papers-list/', views.papers_list, name = "papers_list"),
    path('past-year-papers/<slug:slug>/papers-list/<int:pk>/', views.delete_papers, name = "delete_papers"),
    path('profile/', views.edit_user, name = "profile"),
    path('profile/info/', views.info, name = "info"),
    path('<single_slug>/', views.error_page, name = "error_page"),
    path('accounts/login/',views.login_request, name='login_required')
]

noteKeeper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/views.py
from django.shortcuts import render, redirect
from .models import Department, Subject, Semester, College, UserProfile, Notes, Papers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from .forms import RegistrationForm, LoginForm, UserProfileForm, NotesForm, PapersForm
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

def edit_user(request):
	return render(request = request,
                  template_name = "main/profile.html",
                  context = {"userpro": UserProfile.objects.all})

def homepage(request):
	return render(request = request,
				 template_name = "main/home.html",
				 context = {"department": Department.objects.all})

def error_page(request, single_slug):
	return render(request = request,
				  template_name = "main/error_page.html")

def about(request):
	return render(request = request,
				  template_name = "main/about.html")

def team(request):
	return render(request = request,
				  template_name = "main/team.html")

def register(request):
	if request.method == "POST":
		form = RegistrationForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f"New Account Created: {username}")
			login(request, user)
			messages.info(request, f"You are now logged in as {username}")
			return redirect("main:homepage")

		else:
			username = form.cleaned_data.get('username')
			email = form.cleaned_data.get('email')
			print('######################', form.cleaned_data)
			password1 = form.cleaned_data.get('password1')
			password2 = form.cleaned_data.get('password2')
			print(form.cleaned_data)

			if not username:
				messages.error(request, f"Error: Username already exists")
			elif not email:
				messages.error(request, f"Error: Invalid Email ID")
			elif len(password1) < 8:
				messages.error(request, f"Error: Your password must be at least 8 digits long.")
			elif password1.isdigit():
				messages.error(request, f"Error: Your password cannot be fully numeric.")
			elif not (password1 and password2):
				messages.error(request, f"Error: {form.error_messages['password_mismatch']}")
			form = RegistrationForm()

			return render(request = request,
	                       template_name = "main/register.html",
	                       context={"form":form})

	form = RegistrationForm
	return render(request = request,
                  template_name = "main/register.html",
                  context={"form":form})


def logout_request(request):
	logout(request)
	messages.info(request, f"Logged out successfully!")
	return redirect("main:homepage")

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request = request, data = request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username = username, password = password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}")
				return redirect('main:homepage')
			else:
				messages.error(request, f"Invalid username or password")
		else:
			messages.error(request, f"Invalid username or password")

	form = AuthenticationForm()
	return render(request,
				 "main/login.html",
				 {"form":form})
@login_required
def college(request):
	return render(request,
				  "main/college.html",
				  {"colleges": College.objects.all})
@login_required
def department(request):
	return render(request,
				  "main/department.html",
				  {"department": Department.objects.all})
@login_required
def single_slug(request, single_slug):

	department = [d.department_slug for d in Department.objects.all()]

	if single_slug in department:
		matching_series = Semester.objects.filter(department_name__department_slug = single_slug)
		sem_urls = {}

		for m in matching_series.all():
			part_one = m.sem_slug
			sem_urls[m] = part_one

		return render(request = request,
					  template_name = "main/semester.html",
					  context = {"semester": matching_series, "part_ones": sem_urls})

	semester = [s.sem_slug for s in Semester.objects.all()]

	if single_slug in semester:
		matching_series = Subject.objects.filter(sem__sem_slug = single_slug)
		sub_urls = {}

		for m in matching_series.all():
			part_one = m.sub_slug
			sub_urls[m] = part_one

		return render(request = request,
					  template_name = "main/subject.html",
					  context = {"subject": matching_series, "part_ones": sub_urls})

	subject = [s.sub_slug for s in Subject.objects.all()]

	if single_slug in subject:

		if request.method == 'POST':
			for f in request.FILES.getlist('file_pdf'):
				form = NotesForm(request.POST, request.FILES)
				if form.is_valid():
					obj = form.save(commit=False)
					obj.file_pdf = f
					form.save()
			s = "/notes/" + single_slug + "/notes-list"
			return redirect(s)

		else:
			form = NotesForm()
		return render(request = request,
					  template_name = 'main/files.html',
					  context = {"form": form, "slug": single_slug})

	else:
		return render(request = request,
					  template_name = "main/error_page.html")

@login_required
def paper_single_slug(request, single_slug):

	department = [d.department_slug for d in Department.objects.all()]

	if single_slug in department:
		matching_series = Semester.objects.filter(department_name__department_slug = single_slug)
		sem_urls = {}

		for m in matching_series.all():
			part_one = m.sem_slug
			sem_urls[m] = part_one

		return render(request = request,
					  template_name = "main/semester-papers.html",
					  context = {"semester": matching_series, "part_ones": sem_urls})

	semester = [s.sem_slug for s in Semester.objects.all()]

	if single_slug in semester:

		if request.method == 'POST':
			for f in request.FILES.getlist('file_pdf'):
				form = PapersForm(request.POST, request.FILES)
				if form.is_valid():
					obj = form.save(commit=False)
					obj.file_pdf = f
					form.save()
			s = "/past-year-papers/" + single_slug + "/papers-list"
			return redirect(s)

		else:
			form = PapersForm()
		return render(request = request,
					  template_name = 'main/papers.html',
					  context = {"form": form, "slug": single_slug})

	else:
		return render(request = request,
					  template_name = "main/error_page.html")
@login_required
def notes_list(request, slug):
	slugs = {}
	slugs['slug'] = slug
	return render(request = request,
				  template_name = "main/notes_list.html",
				  context = {"notes": Notes.objects.all, "slugs": slugs})
@login_required
def papers_list(request, slug):
	slugs = {}
	slugs['slug'] = slug
	return render(request = request,
				  template_name = "main/papers_list.html",
				  context = {"papers": Papers.objects.all, "slugs": slugs})
@login_required
def delete_notes(request, slug, pk):
	if request.method == 'POST':
		note = Notes.objects.get(pk = pk)
		note.delete()
	return redirect("main:homepage")
@login_required
def delete_papers(request, slug, pk):
	if request.method == 'POST':
		paper = Papers.objects.get(pk = pk)
		paper.delete()
	return redirect("main:homepage")
@login_required
def info(request):
	if request.method == "POST":
		form = UserProfileForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect("main:profile")
	else:
		form = UserProfileForm()
		return render(request = request,
				  	template_name = "main/info.html",
				  	context = {"form": form})

templates/main/about.html
{% extends "main/header.html" %}
{% load static %}

	{% block content %}
		<style>
			h3 span{
                color:  black;
            }
            h3{
                color:  #242D31;
                font: bold 36px 'Calisto MT', cursive;
                margin: 0;
            }
            p span{
                display:block;
                font-weight: normal;
                font-size:14px;
                line-height:2;
            }
            p a{
                color:  black;
                text-decoration: none;;
            }
            p {
            	color:  #242D31;
                font: normal 20px 'Candara', cursive;
            }
            .space {
            	padding: 50px;
            }
		</style>
		<div class = "container">
			<h3>About Us</h3>
		</div>
		<div class="mdl-grid">
			<div class="mdl-cell mdl-cell--5-col mdl-cell--8-col-tablet">
				<div class = "container">
					<p class = "space"></p>
					<p>College Note Keeper is a platform build in order to provide you all the necessary notes and question papers. Since the pandemic started, we all had to rely on the Internet more than ever for our studies.  So we built this platform where anyone can upload files and everyone else can download them. I've categorised the files with respect to colleges, departments, semesters and subjects so that it becomes easy for you to get what you need.</p>
				</div>
			</div>
			<div class="mdl-cell mdl-cell--6-col mdl-cell--6-col-tablet">
				<img src = "{% static 'images/note-image.jpg' %}" alt="Notes Image">
			</div>
		</div>
	{% endblock %}

templates/main/account.html
{% extends 'main/header.html' %}

{% block content %}
        {% if user.is_authenticated %}
	        <h1>{{ user.username }} Welcome to your profile page</h1>
	        <h2>{{ user.userprofile.username }}</h2>
	        <h2>{{ user.userprofile.college }}</h2>
        {% endif %}

{% endblock %}

templates/main/college.html
{% extends 'main/header.html' %}

			{% block content %}
				<style>
					.college-button {
						padding: 10px;
						width: 400px;
						height: 100px;
					    font-size: 15px;
					    position: relative;
					    bottom: 460%;
					    left: 20%;
					    font-family: "Franklin Gothic Medium";
					    text-transform: uppercase;
					    letter-spacing: 1.5px;
					    font-weight: 500;
					    color: black;
					    background-color: #FFFFFF;
					    border: solid;
					    border-color: #39D229;
					    border-radius: 25px;
					    box-shadow: 0px 8px 15px rgba(15, 69, 8, 0.35);
					}
					.college-button:hover {
					    font-family: "Franklin Gothic Medium";
					    text-transform: uppercase;
					    letter-spacing: 1.5px;
					    font-weight: 500;
					    color: white;
					    background-color: #0E4308;
					    border: solid;
					    border-color: #296821;
					    border-radius: 25px;
					    box-shadow: 0px 8px 15px rgba(15, 69, 8, 0.25);
					}
					.heading {
						font-family: "Verdana";
						font-weight: bold;
						font-size: 35px;
						text-align: center;
						padding: 60px;
					}
				</style>
				<div class = "container">
					<p class = "heading">
						Choose your College
					</p>
				</div>
				<div class="row">
					{% for col in colleges %}
						<div class="col s12 m6 l6">
						<a href = ""><button class="college-button btn-border">{{col.college_name}}</button></a>
					{% endfor %}
				</div>
            {% endblock %}

templates/main/header.html
<head>
  {% load static %}
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href = "{% static 'main/css/material.css' %}", rel = 'stylesheet'>
    <link href = "{% static 'main/css/random-styling.css' %}", rel = 'stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'main/js/material.js' %}"></script>
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <style>
        .mdl-layout .mdl-layout__header--transparent{
            background-color: white;
        }
        h6 {
            padding-bottom: 10px;
        }
        .logo-actual {
            padding-bottom: 5px;
            width: 45px;
        }
        #loading {
            position: relative;
            width: 100%;
            height: 100vh;
            background: #fff
            url('https://thumbs.gfycat.com/PlumpAdolescentArmyant-size_restricted.gif')
            no-repeat center;
            z-index: 99999;
        }
    </style>
</head>
<body onload = "preloader()">
    <div id = "loading"></div>
    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout">
        {% include './includes/navbar.html' %}
        {% include './includes/messages.html' %}
        <main class="mdl-layout__content">
            <div class="page-content"><!-- Content goes here -->
                <br><br>
                {% block content %}
                {% endblock %}
                <br><br>
            </div>
            <script>M.AutoInit();</script>
            {% include './includes/footer.html' %}
        </main>
    </div>
    <script>
        var loader = document.getElementById('loading');
        setTimeout(function preloader(){
            loader.style.display = 'none';
        }, 200);
    </script>
</body>

templates/main/login.html
{% extends 'main/header.html' %}

                {% block content %}
                    {% load static %}
                    <link href = "{% static 'main/css/materialize-1.css' %}", rel = 'stylesheet'>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
                    <br>
                    <style>
                        .strong-login {
                            font-family: Gadget;
                            color: black;
                            font-weight: 550;
                            color: #2980b9;
                            font-size: 17px;
                        }
                        .strong-login:hover {
                            text-decoration: underline;
                        }
                    </style>
                    <div class = 'container'>
                        <form method="post" action="" class="col s12">
                            {% csrf_token %}

                            <div class="row">
                                <div class="input-field col s9">
                                    <input id = "username" name="username" required type="text"/>
                                    <label for="username">Username</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s9">
                                    <input id = "password" name="password" required type="password"/>
                                    <label for="password">Password</label>
                                </div>
                            </div>

                            <input class="sub-button" type="submit" value="Login"/>
                        </form>
                        <p>No account? <a href="/register"><strong class = "strong-login">Register here.</strong></a></p>
                    </div>
                {% endblock %}

templates/main/notes_list.html
{% extends 'main/header.html' %}
    {% block content %}
        <div class = "container">
            <h2>Notes</h2>
        </div>

        <div class = "container">
            <table class = "table">
                <thead>
                    <tr>
                        <th>File Name</th>
                        <th>File Published</th>
                        <th>Download</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for note in notes %}
                        {% if note.sub_slug == slugs.slug %}
                            <tr>
                                <td>{{ note.file_pdf.name }}</td>
                                <td>{{ note.file_published }}</td>
                                <td>
                                    <a href = "{{ note.file_pdf.url }}" class = "btn" target = "_blank">Download</a>
                                </td>
                                <td>
                                    <form method="post" action = "{% url 'main:delete_notes' slugs.slug note.pk %}">
                                        {% csrf_token %}
                                        <button type = "submit" class = "btn">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endblock %}

templates/main/papers.html
{% extends 'main/header.html' %}

{% load static %}

{% block content %}
        <link href = "{% static 'main/css/file-paper.css' %}", rel = 'stylesheet'>
        <a href = "papers-list"><button class = "notes-button">Get Papers</button></a>
        <div class = 'container'>
            <div class="row">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}                    
                    <div class="row">
                        <div class="input-field col s9">
                            {{ form.file_published }}
                            <span class="helper-text" data-error="wrong" data-success="right">Date Published</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s9">
                            <input value="{{ slug }}" name = "sem_slug" id="sem_slug" type="text" class="validate" multiple/>
                            <label for="sem_slug">Semester</label>
                            <span class="helper-text" data-error="wrong" data-success="right">Categorises the papers semester-wise</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s9">
                            <div class="file-field input-field">
                              <div class="btn">
                                <span>Choose File</span>
                                <input name = "file_pdf" id = "file_pdf" type="file" required multiple>
                              </div>
                              <div class="file-path-wrapper">
                                <input class="file-path validate" type="text" placeholder="Upload one or more files">
                              </div>
                            </div>
                        </div>
                    </div>
                    <input class = "sub-button" type="submit" value="Upload"/>
                </form>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <p class = "big">Folder Upload</p>
            <p class = "big">&nbsp;</p>
        </div>
        <div class = 'container'>
            <div class="row">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}                    
                    <div class="row">
                        <div class="input-field col s9">
                            {{ form.file_published }}
                            <span class="helper-text" data-error="wrong" data-success="right">Date Published</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s9">
                            <input value="{{ slug }}" name = "sem_slug" id="sem_slug" type="text" class="validate" multiple/>
                            <label for="sem_slug">Semester</label>
                            <span class="helper-text" data-error="wrong" data-success="right">Categorises the papers semester-wise</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s9">
                            <div class="file-field input-field">
                              <div class="btn">
                                <span>Choose Folder</span>
                                <input type="file" id="file_pdf" name="file_pdf" webkitdirectory directory/>
                                <input type="text" id="directories" name="directories" hidden />
                              </div>
                              <div class="file-path-wrapper">
                                <input class="file-path validate" type="text" placeholder="Upload folder">
                              </div>
                            </div>
                        </div>
                    </div>
                    <input class = "sub-button" type="submit" value="Upload"/>
                </form>
            </div>
        </div>
        <script>
         files = document.querySelector("#file_pdf").files;
         document.querySelector("#file_pdf").addEventListener("change", function() {
            files = document.querySelector("#file_pdf").files;
            var directories = {}
            for (var file of files) {
              file.webkitRelativePath
              directories[file.name] = file.webkitRelativePath
            }
            directories = JSON.stringify(directories);
            document.querySelector("#directories").value = directories
         });
        </script>
{% endblock %}

templates/main/papers_list.html
{% extends 'main/header.html' %}
    {% block content %}
        <div class = "container">
            <h2>Papers</h2>
        </div>

        <div class = "container">
            <table class = "table">
                <thead>
                    <tr>
                        <th>File Name</th>
                        <th>File Published</th>
                        <th>Download</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for paper in papers %}
                        {% if paper.sem_slug == slugs.slug %}
                            <tr>
                                <td>{{ paper.file_pdf.name }}</td>
                                <td>{{ paper.file_published }}</td>
                                <td>
                                    <a href = "{{ paper.file_pdf.url }}" class = "btn" target = "_blank">Download</a>
                                </td>
                                <td>
                                    <form method="post" action = "{% url 'main:delete_papers' slugs.slug paper.pk %}">
                                        {% csrf_token %}
                                        <button type = "submit" class = "btn">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endblock %}

templates/main/profile.html
{% extends 'main/header.html' %}
    {% block content %}
        <style>
            .text{
                text-align: center;
            }
            .edit:hover{
                font-family: Gadget;
                text-decoration: underline;
                color: black;
            }
        </style>
        <div class = "text">
            {% for users in userpro %}
                <p>{{ users.first_name }}</p>
                <p>{{ users.last_name }}</p>
                <p>{{ users.city }}</p>                
            {% endfor %}
            <a class = "edit" href="/profile/info">Edit info</a>

        </div>
    {% endblock %}

templates/main/register.html
{% extends "main/header.html" %}

                {% block content %}
                    {% load static %}
                    <link href = "{% static 'main/css/materialize-1.css' %}", rel = 'stylesheet'>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
                    <br>
                    <style>
                        .strong-login {
                            font-family: Gadget;
                            color: black;
                            font-weight: 550;
                            color: #2980b9;
                            font-size: 17px;
                        }
                        .strong-login:hover {
                            text-decoration: underline;
                        }
                    </style>
                    <div class = 'container'>
                        <div class="row">
                            <form method="post" action="" class="col s12">
                                {% csrf_token %}
                                
                                <div class="row">
                                    <div class="input-field col s9">
                                        <input id = "username" name="username" type="text" required data-length="10" class="validate"/>
                                        <label for="username">Username</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s9">
                                        <input id = "email" name="email" type="email" required class="validate"/>
                                        <label for="email">Email</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s9">
                                        <input id = "college" name="college" type="text" required class="validate"/>
                                        <label for="college">College</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s9">
                                        <input id="password1" name="password1" type="password" required class="validate"/>
                                        <label for="password1">Password</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s9">
                                        <input id="password2" name="password2" type="password" required class="validate"/>
                                        <label for="password2">Confirm Password</label>
                                    </div>
                                </div>
                                <input class = "sub-button" type="submit" value="Register"/>
                            </form>
                        </div>
                        If you already have an account <a href="/login"><strong class = "strong-login">login</strong></a> instead.
                    </div>

                {% endblock %}

templates/main/semester-papers.html
{% extends 'main/header.html' %}

			{% block content %}
			{% load static %}
				<link href = "{% static 'main/css/department-style.css' %}", rel = 'stylesheet'>
				<div class = "container">
					<p class = "heading">
						Semester
					</p>
				</div>
				<div class = "container">
					<div class="row">
				        {% for sem, partone in part_ones.items %}
				            <div class="col s12 m6 l6">
				                <a href="/past-year-papers/{{partone}}", style="color:#000">
				                    <button class="college-button btn-border">{{sem.sem}}</button>
				                    <p class = "big">&nbsp;</p>
				                </a>
				            </div>
				        {% endfor %}
			    	</div>
			    </div>
            {% endblock %}

templates/main/semester.html
{% extends 'main/header.html' %}

			{% block content %}
			{% load static %}
				<link href = "{% static 'main/css/department-style.css' %}", rel = 'stylesheet'>
				<div class = "container">
					<p class = "heading">
						Semester
					</p>
				</div>
				<div class = "container">
					<div class="row">
				        {% for sem, partone in part_ones.items %}
				            <div class="col s12 m6 l6">
				                <a href="/notes/{{partone}}", style="color:#000">
				                    <button class="college-button btn-border">{{sem.sem}}</button>
				                    <p class = "big">&nbsp;</p>
				                </a>
				            </div>
				        {% endfor %}
			    	</div>
			    </div>
            {% endblock %}

templates/main/subject.html
{% extends 'main/header.html' %}

			{% block content %}
			{% load static %}
				<link href = "{% static 'main/css/department-style.css' %}", rel = 'stylesheet'>
				<div class = "container">
					<p class = "heading">
						Subjects
					</p>
				</div>
				<div class = "container">
					<div class="row">
				        {% for sub, partone in part_ones.items %}
				            <div class="col s12 m6 l6">
				                <a href="/notes/{{partone}}", style="color:#000">
				                    <button class="college-button btn-border">{{sub.sub_name}}</button>
				                    <p class = "big">&nbsp;</p>
				                </a>
				            </div>
				        {% endfor %}
			    	</div>
			    </div>
            {% endblock %}